spring.datasource.url=jdbc:mysql://localhost:3306/taskscheduler
spring.datasource.username=root
spring.datasource.password=Pavan@2002

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pavannayak1205@gmail.com
spring.mail.password=mqqu mpfl rtfm pviq

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true